[package]
name = "fast-rehnda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.2"
glam = "0.22"
winit = "0.27.5"

log = "0.4"
simplelog = "0.12"